// ---------------------------------------------------------------
// Talks data – edit this file to add, remove, or update entries.
//
//   date:     "YYYY-MM"  (e.g. "2026-05" for May 2026)
//   event:    name of the event, seminar, or colloquium
//   location: institution and/or city, country (or "Virtual")
//
// To add a talk, copy any { … } block and change the values.
// The page sorts automatically – order here does not matter.
// ---------------------------------------------------------------

const talks = [
  { date: "2026-12-2", event: "Seminar talk", location: "Princeton University, USA" },
  { date: "2026-12-1", event: "Seminar talk", location: "Bard College, USA" },
  { date: "2026-11", event: "Materials Research Society Fall Meeting", location: "Boston, USA" },
  { date: "2026-10", event: "Seminar talk", location: "Donostia International Physics Center, Spain" },
  { date: "2026-06-02", event: "Quantum Matter Frontiers: Entanglement, Symmetry, and Emergence", location: "KIAS, Seoul, South Korea" },
  { date: "2026-06-03", event: "Young Research Leaders in Topological Materials and Beyond", location: "KIAS, Seoul, South Korea" },
  { date: "2026-06-01", event: "Seminar talk", location: "TU Munich, Germany" },
  { date: "2026-01", event: "New Frontiers of Geometry and Topology in Condensed Matter Physics", location: "University of Tokyo, Japan" },
  { date: "2025-12", event: "Seminar talk", location: "University of Leeds, UK" },
  { date: "2025-11", event: "Seminar talk", location: "University of Warwick, UK" },
  { date: "2025-11", event: "2 seminar talks", location: "University of St Andrews, UK" },
  { date: "2025-10", event: "Seminar talk", location: "Lancaster University, UK" },
  { date: "2025-08", event: "Summer School on Symmetry Protected Topological Phases", location: "Physikzentrum Bad Honnef, Germany" },
  { date: "2025-07", event: "Young Research Leaders in Topological Materials and Beyond", location: "Rice Global Paris Center, France" },
  { date: "2025-06", event: "Condensed Matter and Quantum Materials", location: "University of Bristol, UK" },
  { date: "2025-04", event: "Spring School on Electron Correlations and Topology", location: "Rice University, Houston, USA" },
  { date: "2025-03", event: "Seminar talk", location: "City St George's, University of London, UK" },
  { date: "2024-11", event: "Seminar talk", location: "Institut N\u00e9el, Grenoble, France" },
  { date: "2024-09", event: "Non-Hermitian Topology, Geometry, and Symmetry", location: "Simons Center for Geometry and Physics, Stony Brook, USA" },
  { date: "2024-06", event: "Seminar talk", location: "University of Oxford, UK" },
  { date: "2024-05", event: "Quantum Information and Quantum Matter", location: "NYU Abu Dhabi, UAE" },
  { date: "2024-05", event: "Seminar talk", location: "University of Manchester, UK" },
  { date: "2024-04", event: "Recently Appointed Academic Talks", location: "Thomas Young Centre, London, UK" },
  { date: "2024-03", event: "Seminar talk", location: "University of Birmingham, UK" },
  { date: "2024-02", event: "Seminar talk", location: "King's College London, UK" },
  { date: "2024-02", event: "Nordic and UK Virtual Condensed Matter Seminar", location: "Virtual" },
  { date: "2024-02", event: "Seminar talk", location: "Imperial College London, UK" },
  { date: "2024-01", event: "Seminar talk", location: "Queen Mary University of London, UK" },
  { date: "2024-01", event: "Seminar talk", location: "MPI-FKF, Stuttgart, Germany" },
  { date: "2023-11", event: "Seminar talk", location: "University of Cambridge, UK" },
  { date: "2023-09", event: "Korrelationstage (keynote)", location: "MPI-PKS, Dresden, Germany" },
  { date: "2023-08", event: "Summer School: Physics by the Lake", location: "University of Stirling, UK" },
  { date: "2023-07", event: "Condensed Matter in the City", location: "University College London, UK" },
  { date: "2023-06", event: "Physics Department Colloquium", location: "Drexel University, Philadelphia, USA" },
  { date: "2023-05", event: "Quantum Information and Quantum Matter", location: "NYU Abu Dhabi, UAE" },
  { date: "2023-03", event: "APS March Meeting (keynote)", location: "Las Vegas, USA" },
  { date: "2023-03", event: "Seminar talk", location: "Rutgers University, USA" },
  { date: "2023-01", event: "Physics Department Colloquium", location: "Imperial College London, UK" },
  { date: "2023-01", event: "Seminar talk", location: "Columbia University, New York, USA" },
  { date: "2022-11", event: "Seminar talk", location: "Institute for Advanced Study, Princeton, USA" },
  { date: "2022-11", event: "Seminar talk", location: "Stony Brook University, USA" },
  { date: "2022-08", event: "Condensed Matter Summer Camp", location: "Paul Scherrer Institute, Switzerland" },
  { date: "2022-06", event: "Gordon Research Seminar on Correlated Electron Systems", location: "Mount Holyoke College, USA" },
  { date: "2022-05", event: "Geometrical Aspects of Topological Phases", location: "Simons Center for Geometry and Physics, Stony Brook, USA" },
  { date: "2022-05", event: "Seminar talk", location: "University of Zurich, Switzerland" },
  { date: "2022-02", event: "Physics EDI Initiative Research Talk", location: "Princeton University, USA" },
  { date: "2021-11", event: "Seminar talk", location: "Princeton Quantum Initiative, USA" },
  { date: "2020-10", event: "Seminar talk", location: "Princeton Center for Theoretical Science, USA" },
  { date: "2020-05", event: "Condensed Matter Young Researchers Meeting", location: "ETH Zurich, Switzerland" },
  { date: "2019-12", event: "Seminar talk", location: "Cornell University, USA" },
  { date: "2019-12", event: "Seminar talk", location: "Microsoft Research Station Q, USA" },
  { date: "2019-10", event: "Young Research Leaders Workshop", location: "University of Mainz, Germany" },
  { date: "2019-09", event: "Seminar talk", location: "University of Utrecht, Netherlands" },
  { date: "2019-07", event: "ToCoTronics Colloquium", location: "University of W\u00fcrzburg, Germany" },
  { date: "2019-06", event: "Seminar talk", location: "UC Berkeley, USA" },
  { date: "2019-02", event: "Seminar talk", location: "Kavli Institute for Theoretical Physics, Santa Barbara, USA" },
  { date: "2018-10", event: "Seminar talk", location: "University of Zurich, Switzerland" },
  { date: "2018-05", event: "Seminar talk", location: "University of Cambridge, UK" },
  { date: "2018-04", event: "Seminar talk", location: "Karlsruhe Institute of Technology, Germany" },
  { date: "2017-11", event: "Seminar talk", location: "University of Cologne, Germany" },
  { date: "2017-11", event: "Seminar talk", location: "Paul Scherrer Institute, Switzerland" },
  { date: "2017-09", event: "Seminar talk", location: "RIKEN, Japan" },
];
